import 'dart:typed_data';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class BlueprintPdfGenerator {
  /// 🏛️ Dynamically Generates and Downloads the PDF Blueprint on the phone
  static Future<void> generateAndInstallDocument({
    required BuildContext context,
    required String documentTitle,
    required String categoryName,
    required Map<String, dynamic> blueprint,
    required List<dynamic> content,
    String studentName = 'N/A',
    String fatherName = 'N/A',
    String rawText = '',
    String? printLanguage, // 'original', 'translated', or 'bilingual'
  }) async {
    final pdf = pw.Document();
    
    // Dynamic high-fidelity Google Fonts to prevent tofu character box rendering in PDFs!
    final defaultFont = await PdfGoogleFonts.robotoRegular();
    final urduFont = await PdfGoogleFonts.amiriRegular(); // Amiri provides perfect Arabic/Urdu cursive script mapping

    // Parse Blueprint parameters
    final String bpTitle = blueprint['title'] ?? 'Standard Blueprint';
    final String footerNote = blueprint['footer_note'] ?? 'Generated by Starlight Vault Terminal.';

    final List<List<String>> tableData = [];
    final String tappedCategory = categoryName.toLowerCase();
    final bool isScannedDoc = tappedCategory == 'scanned documents' || tappedCategory == 'scanned';

    // Dynamically resolve bilingual headers based on print language choice
    String finalTitle = documentTitle;
    final bool isTranslation = tappedCategory == 'translation' || tappedCategory == 'translated document';
    
    if (isTranslation && content.length >= 2 && content[0] is Map && content[1] is Map) {
      if (printLanguage == 'original') {
        finalTitle = "${content[0]['title']} - ${content[1]['title']}".toUpperCase();
      } else if (printLanguage == 'translated') {
        finalTitle = "${content[0]['translated_text']} - ${content[1]['translated_text']}";
      } else {
        finalTitle = "${content[0]['title']} - ${content[0]['translated_text']}".toUpperCase();
      }
    }

    // 🏛️ Schema Logic: Only format Table Data if it's NOT a scanned plain-text document
    if (!isScannedDoc) {
      if (tappedCategory == 'datesheets') {
        // DateSheets Column Layout
        tableData.add(['DATE & DAY', 'SUBJECT', 'TIME & DURATION', 'VENUE']); // Headers

        for (var entry in content) {
          if (entry is Map) {
            final String date = entry['date']?.toString() ?? 'N/A';
            final String day = entry['day']?.toString() ?? '';
            final String dateDayLabel = day.isNotEmpty ? "$date ($day)" : date;
            final String subject = entry['subject_name']?.toString() ?? 'Untitled';
            final String time = entry['time']?.toString() ?? 'N/A';
            final String duration = entry['duration_mins']?.toString() ?? '0';
            final String timeDurationLabel = "$time ($duration mins)";
            final String venue = entry['venue']?.toString() ?? 'Main Hall';

            tableData.add([dateDayLabel, subject, timeDurationLabel, venue]);
          }
        }
      } else if (tappedCategory == 'fee vouchers data' || tappedCategory == 'fees') {
        // Fee Vouchers Column Layout
        tableData.add(['STUDENT & FATHER', 'FEE CATEGORY/ITEM', 'LEDGER KEY', 'AMOUNT (PKR)']); // Headers

        for (var entry in content) {
          if (entry is Map) {
            final String feeType = entry['fee_type'] ?? entry['label'] ?? 'Custom Fee Item';
            final String key = entry['key'] ?? 'fee_item';
            final String amount = (entry['amount'] ?? 0).toString();

            tableData.add([
              "$studentName\n($fatherName)",
              feeType,
              key,
              "PKR $amount",
            ]);
          }
        }
      } else if (tappedCategory == 'marksheets and tests' || tappedCategory == 'results') {
        // Marksheets Column Layout
        tableData.add(['STUDENT & FATHER', 'ROLL NO', 'OBTAINED MARKS', 'GRADE & STATUS']); // Headers

        for (var entry in content) {
          if (entry is Map) {
            final String name = entry['student_name']?.toString() ?? 'Unknown';
            final String father = entry['father_name']?.toString() ?? 'N/A';
            final String roll = entry['roll_number']?.toString() ?? 'N/A';
            final String obtained = entry['marks_obtained']?.toString() ?? '0';
            final String max = entry['max_marks']?.toString() ?? '100';
            final String percent = (double.tryParse(entry['percentage']?.toString() ?? '0.0') ?? 0.0).toStringAsFixed(1);
            final String grade = entry['grade']?.toString() ?? 'F';
            final String status = entry['status']?.toString().toUpperCase() ?? 'FAIL';

            tableData.add([
              "$name\n($father)",
              roll,
              "$obtained / $max\n($percent%)",
              "Grade $grade\n($status)",
            ]);
          }
        }
      } else if (tappedCategory == 'students attendances and staff attendances' || tappedCategory == 'attendance') {
        // Attendance Session Column Layout
        tableData.add(['MEMBER NAME & FATHER', 'IDENTIFIER ID', 'DEPT/CLASS', 'DAILY STATUS']); // Headers

        for (var entry in content) {
          if (entry is Map) {
            final String name = entry['student_name'] ?? entry['staff_name'] ?? 'Unknown Name';
            final String subDetail = entry['father_name'] ?? entry['role'] ?? 'N/A';
            final String nameLabel = "$name\n($subDetail)";

            final String id = entry['student_id'] ?? entry['staff_id'] ?? 'N/A';
            final String idLabel = id.length > 8 ? id.substring(0, 8) + '...' : id;

            final String deptClass = entry['department'] ?? entry['class_sec'] ?? 'General';

            final String status = entry['status']?.toString().toUpperCase() ?? 'ABSENT';

            tableData.add([
              nameLabel,
              idLabel,
              deptClass,
              status,
            ]);
          }
        }
      } else if (tappedCategory == 'translation' || tappedCategory == 'translated document') {
        // Custom Translation Layout based on user language choice
        if (printLanguage == 'original') {
          tableData.add(['ORIGINAL SPECIFICATIONS / CODES']); // Headers
          for (var entry in content) {
            if (entry is Map) {
              tableData.add([
                entry['title']?.toString() ?? '',
              ]);
            }
          }
        } else if (printLanguage == 'translated') {
          tableData.add(['URDU / TRANSLATED TEXT']); // Headers
          for (var entry in content) {
            if (entry is Map) {
              tableData.add([
                entry['translated_text']?.toString() ?? '',
              ]);
            }
          }
        } else {
          // Default Side-by-Side Bilingual
          tableData.add(['TRANSLATED CODES & SPECIFICATIONS', 'URDU / TRANSLATED TEXT']); // Headers
          for (var entry in content) {
            if (entry is Map) {
              tableData.add([
                entry['title']?.toString() ?? 'Document Text',
                entry['translated_text']?.toString() ?? 'N/A',
              ]);
            }
          }
        }
      } else {
        // Syllabus Column Layout (Default)
        tableData.add(['CLASS/LEVEL', 'CHAPTER/UNIT', 'TOPICS & KEYWORDS']); // Headers

        for (var classObj in content) {
          if (classObj is Map) {
            final String classTitle = classObj['title'] ?? classObj['name'] ?? 'General Class';
            final List<dynamic> chapters = classObj['chapters'] ?? [];
            
            for (var chapter in chapters) {
              if (chapter is Map) {
                final String chapterName = chapter['name'] ?? 'Untitled Chapter';
                final List<dynamic> topics = chapter['topics'] ?? [];
                final String topicsJoined = topics.join(', ');

                tableData.add([
                  classTitle,
                  chapterName,
                  topicsJoined.isNotEmpty ? topicsJoined : 'N/A',
                ]);
              }
            }
          }
        }
      }
    }

    // Build PDF Layout
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(bottom: 20),
            child: pw.Text(
              "STARLIGHT INSTITUTION DEPLOYMENT",
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500, fontWeight: pw.FontWeight.bold),
            ),
          );
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.center,
            margin: const pw.EdgeInsets.only(top: 20),
            child: pw.Column(
              children: [
                pw.Divider(color: PdfColors.grey300, thickness: 1),
                pw.SizedBox(height: 8),
                pw.Text(
                  isScannedDoc ? "Official Scanned Record Directory." : footerNote,
                  style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  "Page ${context.pageNumber} of ${context.pagesCount}",
                  style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
                ),
              ],
            ),
          );
        },
        build: (pw.Context context) {
          final List<pw.Widget> widgets = [
            // Institutional Header with explicit Logo space!
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  if (isTranslation)
                    // Beautiful Circular Placeholder for logo (on the Left for RTL)
                    pw.Container(
                      width: 60,
                      height: 60,
                      decoration: pw.BoxDecoration(
                        border: pw.Border.all(color: PdfColors.indigo300, width: 1.5, style: pw.BorderStyle.dashed),
                        shape: pw.BoxShape.circle,
                      ),
                      alignment: pw.Alignment.center,
                      child: pw.Text("LOGO", style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo400)),
                    ),
                  
                  pw.Column(
                    crossAxisAlignment: isTranslation ? pw.CrossAxisAlignment.end : pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        finalTitle,
                        textDirection: isTranslation ? pw.TextDirection.rtl : pw.TextDirection.ltr,
                        style: pw.TextStyle(
                          font: isTranslation ? urduFont : defaultFont,
                          fontSize: isTranslation ? 18 : 22, 
                          fontWeight: pw.FontWeight.bold, 
                          color: PdfColors.indigo900,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        isScannedDoc ? "Digital OCR Extracted Text" : "Blueprint Ref: $bpTitle",
                        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                      ),
                    ],
                  ),
                  
                  if (!isTranslation)
                    // Beautiful Circular Placeholder for logo (on the Right for LTR)
                    pw.Container(
                      width: 60,
                      height: 60,
                      decoration: pw.BoxDecoration(
                        border: pw.Border.all(color: PdfColors.indigo300, width: 1.5, style: pw.BorderStyle.dashed),
                        shape: pw.BoxShape.circle,
                      ),
                      alignment: pw.Alignment.center,
                      child: pw.Text("LOGO", style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo400)),
                    ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Category Title Badge
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
              decoration: pw.BoxDecoration(
                color: isScannedDoc ? PdfColors.teal50 : PdfColors.indigo50,
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Text(
                "OFFICIAL ${categoryName.toUpperCase()} VAULT REGISTRY",
                style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: isScannedDoc ? PdfColors.teal900 : PdfColors.indigo900),
              ),
            ),
            pw.SizedBox(height: 24),
          ];

          // 🏛️ Dynamic Layout: Render content (either high-fidelity table or paginated plain text!)
          if (isScannedDoc) {
            // Split the raw OCR text into lines or paragraphs to let it flow across multiple pages cleanly!
            final List<String> lines = rawText.split('\n');
            for (var line in lines) {
              if (line.trim().isNotEmpty) {
                // Determine if line looks like a header (e.g. starts with #)
                if (line.startsWith('##')) {
                  widgets.add(pw.Header(
                    level: 1,
                    child: pw.Text(line.replaceAll('##', '').replaceAll('**', '').trim(), style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
                  ));
                } else if (line.startsWith('#')) {
                  widgets.add(pw.Header(
                    level: 0,
                    child: pw.Text(line.replaceAll('#', '').replaceAll('**', '').trim(), style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
                  ));
                } else {
                  // Render standard paragraph line
                  widgets.add(pw.Paragraph(
                    text: line.replaceAll('**', '').trim(),
                    style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey900, lineSpacing: 4),
                  ));
                }
              } else {
                // Add spacer for empty lines
                widgets.add(pw.SizedBox(height: 8));
              }
            }
          } else {
            if (tappedCategory == 'uploads') {
              final dynamic uploadContent = content.isNotEmpty ? content.first : null;
              if (uploadContent is Map && uploadContent.containsKey('base64')) {
                try {
                  final String b64Str = uploadContent['base64'];
                  final Uint8List imageBytes = base64Decode(b64Str);
                  final pw.MemoryImage memoryImage = pw.MemoryImage(imageBytes);
                  widgets.add(pw.Center(
                    child: pw.Image(memoryImage, fit: pw.BoxFit.contain, height: 400),
                  ));
                } catch (e) {
                  widgets.add(pw.Text("Failed to render uploaded file: $e", style: const pw.TextStyle(fontSize: 12, color: PdfColors.red900)));
                }
              } else {
                widgets.add(pw.Text("No uploaded document content available to print.", style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600)));
              }
            } else if (tableData.length > 1) {
              final isTranslation = tappedCategory == 'translation' || tappedCategory == 'translated document';
              widgets.add(
                pw.TableHelper.fromTextArray(
                  headers: tableData[0],
                  data: tableData.sublist(1),
                  border: pw.TableBorder.all(color: PdfColors.grey300, width: 1),
                  headerStyle: pw.TextStyle(font: defaultFont, fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 9),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.indigo900),
                  rowDecoration: const pw.BoxDecoration(color: PdfColors.white),
                  oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey50),
                  cellBuilder: (col, data, row) {
                    final text = data.toString();
                    final isUrdu = isTranslation && (printLanguage == 'translated' || col == 1);
                    return pw.Container(
                      alignment: isUrdu ? pw.Alignment.centerRight : pw.Alignment.centerLeft,
                      padding: const pw.EdgeInsets.all(10),
                      child: pw.Text(
                        text,
                        textDirection: isUrdu ? pw.TextDirection.rtl : pw.TextDirection.ltr,
                        textAlign: isUrdu ? pw.TextAlign.right : pw.TextAlign.left,
                        style: pw.TextStyle(
                          font: isUrdu ? urduFont : defaultFont,
                          fontSize: isUrdu ? 11 : 9, // Amiri font usually renders slightly smaller, so we size it up to 11
                          color: PdfColors.grey900,
                        ),
                      ),
                    );
                  },
                )
              );
            } else {
              widgets.add(pw.Text("No data structures available for this document.", style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600)));
            }
          }

          return widgets;
        },
      ),
    );

    try {
      // 🏛️ Print or Install PDF Document directly on the phone
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: '${documentTitle.replaceAll(' ', '_')}_blueprint.pdf',
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Failed to install blueprint: $e"), backgroundColor: Colors.red),
      );
    }
  }
}
